name: Run linters and tests

on: [push, pull_request]

jobs:

  run-linters-and-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ğŸ“ Check typing and format
      run: |
        make check-format
        make check-typing
    - name: ğŸ§ª Run all tests with coverage
      run: |
        make test-coverage
    - name: ğŸ“¤ Upload Test Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: htmlcov
    - name: ğŸ§Ÿ Run mutation testing
      run: |
        make test-run-mutation
        make test-generate-mutation-html-report
    - name: ğŸ“¤ Upload Mutation Test Report
      uses: actions/upload-artifact@v4
      with:
        name: mutmut-html-report
        path: html/src
