name: Run linters and tests

on: [push, pull_request]

jobs:

  run-linters-and-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check typing and format
      run: |
        make check-format
        make check-typing
    - name: Run all tests with coverage
      run: |
        make test-coverage
    - name: Run mutation testing
      run: |
        make test-run-mutation
        make test-generate-mutation-html-report
    - name: ðŸ“¤ Upload Mutation Test Report
      uses: actions/upload-artifact@v2
      with:
        name: mutmut-html-report
        path: html/src
